"""Classical image measurements and deterministic silhouette fitting helpers.

This module uses Blender's image decoder and ordinary pixel measurements. It
does not call a learned model or a remote service. A single front image only
constrains the front silhouette; depth and the unseen back remain generated by
the Atlas anatomical shape prior.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path
from typing import Callable

import bpy


def measure_front_reference(path: Path, working_size: int = 512) -> dict:
    """Measure a full-body subject on transparency or a plain background.

    The result contains the subject's width at normalized heights. Pixels are
    downsampled before analysis to bound memory and suppress tiny edge details.
    """
    path = path.expanduser().resolve(strict=True)
    image = bpy.data.images.load(str(path), check_existing=False)
    source_width, source_height = image.size
    if source_width < 32 or source_height < 32:
        bpy.data.images.remove(image)
        raise ValueError(f"Blender could not decode a usable reference image: {path}")
    width, height = source_width, source_height
    scale = min(1.0, working_size / max(width, height))
    if scale < 1.0:
        image.scale(max(1, round(width * scale)), max(1, round(height * scale)))
    width, height = image.size
    rgba = list(image.pixels[:])
    bpy.data.images.remove(image)
    if width < 32 or height < 32:
        raise ValueError("Reference image must be at least 32 by 32 pixels.")

    def color_at(x: int, y: int) -> tuple[float, float, float, float]:
        offset = (y * width + x) * 4
        return tuple(float(value) for value in rgba[offset:offset + 4])

    corners = [color_at(x, y) for x, y in ((0, 0), (width - 1, 0), (0, height - 1), (width - 1, height - 1))]
    transparent = any(color[3] < 0.98 for color in corners)
    background = tuple(sum(color[channel] for color in corners) / len(corners) for channel in range(3))
    mask = bytearray(width * height)
    x_min, x_max, y_min, y_max = width, -1, height, -1
    for y in range(height):
        for x in range(width):
            red, green, blue, alpha = color_at(x, y)
            if transparent:
                foreground = alpha > 0.08
            else:
                distance = math.sqrt((red - background[0]) ** 2 + (green - background[1]) ** 2 + (blue - background[2]) ** 2)
                foreground = alpha > 0.08 and distance > 0.12
            if foreground:
                mask[y * width + x] = 1
                x_min, x_max = min(x_min, x), max(x_max, x)
                y_min, y_max = min(y_min, y), max(y_max, y)

    if x_max < x_min or y_max < y_min:
        raise ValueError("No foreground found. Use a transparent PNG or a plain contrasting background.")
    subject_width, subject_height = x_max - x_min + 1, y_max - y_min + 1
    if subject_height < height * 0.45 or subject_width / subject_height > 1.8:
        raise ValueError("Reference must show one mostly upright, full-body character from the front.")

    # Image buffers are bottom-up in Blender. Produce a bottom-to-top width
    # curve, with gaps interpolated so crossed legs and separated features do
    # not collapse the generated cross-section.
    bins = 128
    widths: list[float | None] = [None] * bins
    for row in range(y_min, y_max + 1):
        foreground_x = [x for x in range(x_min, x_max + 1) if mask[row * width + x]]
        if not foreground_x:
            continue
        z_fraction = (row - y_min) / max(1, subject_height - 1)
        index = min(bins - 1, max(0, int(z_fraction * bins)))
        measured = (max(foreground_x) - min(foreground_x) + 1) / subject_height
        widths[index] = max(widths[index] or 0.0, measured)

    present = [index for index, value in enumerate(widths) if value is not None]
    if not present:
        raise ValueError("Could not extract a character silhouette from the image.")
    for index in range(bins):
        if widths[index] is not None:
            continue
        below = max((candidate for candidate in present if candidate < index), default=None)
        above = min((candidate for candidate in present if candidate > index), default=None)
        if below is None:
            widths[index] = float(widths[above])
        elif above is None:
            widths[index] = float(widths[below])
        else:
            amount = (index - below) / (above - below)
            widths[index] = float(widths[below]) * (1 - amount) + float(widths[above]) * amount

    # Smooth 5 samples to suppress isolated pixels while retaining shoulders,
    # waist, hips, and limb transitions.
    smoothed = []
    for index in range(bins):
        neighbors = [float(widths[position]) for position in range(max(0, index - 2), min(bins, index + 3))]
        smoothed.append(sum(neighbors) / len(neighbors))

    return {
        "schema": "atlas-character-image-measurements/v1",
        "source_image": path.name,
        "source_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "source_dimensions": [int(source_width), int(source_height)],
        "analysis_dimensions": [int(width), int(height)],
        "background_method": "alpha" if transparent else "corner_color_distance",
        "silhouette_bounds_px": [int(x_min), int(y_min), int(x_max), int(y_max)],
        "subject_width_over_height": round(subject_width / subject_height, 6),
        "front_width_profile": [
            {"z": round(index / (bins - 1), 6), "width_over_height": round(value, 6)}
            for index, value in enumerate(smoothed)
        ],
        "inference_policy": {
            "method": "front_silhouette_fit_with_symmetry_and_atlas_anatomy_prior",
            "unseen_depth": "generated from the profile's anatomical depth ratios",
            "unseen_back": "generated from the symmetric procedural body prior",
            "learned_model": False,
            "remote_service": False,
        },
    }


def fit_mesh_to_front_profile(
    vertices, measurements: dict, strength: float = 0.85,
) -> tuple[dict, Callable[[float], float]]:
    """Warp mesh X by height to match a measured front silhouette.

    Z and Y remain governed by the Atlas model. Scale is clamped so a noisy or
    mismatched reference cannot stretch or collapse a region without limit.
    The returned function applies the same X warp to anatomical markers.
    """
    if not 0.0 <= strength <= 1.0:
        raise ValueError("Image fit strength must be between 0 and 1.")
    coordinates = [(float(vertex.co.x), float(vertex.co.z)) for vertex in vertices]
    z_values = [coordinate[1] for coordinate in coordinates]
    low_z, high_z = min(z_values), max(z_values)
    height = high_z - low_z
    if height <= 1e-6:
        raise ValueError("Generated body has no height to fit against the reference.")
    samples = measurements["front_width_profile"]
    current_widths: list[float] = []
    target_widths: list[float] = []
    scales: list[float] = []
    bin_count = len(samples)
    bins: list[list[float]] = [[] for _ in range(bin_count)]
    for x, vertex_z in coordinates:
        index = min(bin_count - 1, max(0, int((vertex_z - low_z) / height * (bin_count - 1))))
        bins[index].append(x)

    def width_near(source_bins: list[list[float]], index: int) -> float:
        # Match the original 2.5-bin sampling band without rescanning every
        # vertex for each profile sample.
        nearby = [
            value
            for bucket_index in range(max(0, index - 2), min(bin_count, index + 3))
            for value in source_bins[bucket_index]
        ]
        return max(nearby) - min(nearby) if len(nearby) >= 2 else 0.0

    for sample_index, sample in enumerate(samples):
        width = width_near(bins, sample_index)
        target = float(sample["width_over_height"]) * height
        current_widths.append(width)
        target_widths.append(target)
        ratio = target / width if width > 1e-6 else 1.0
        scales.append(max(0.65, min(1.55, ratio ** strength)))

    def scale_at_z(z_value: float) -> float:
        position = max(0.0, min(1.0, (float(z_value) - low_z) / height)) * (len(scales) - 1)
        lower = int(position)
        upper = min(len(scales) - 1, lower + 1)
        amount = position - lower
        return scales[lower] * (1 - amount) + scales[upper] * amount

    for vertex in vertices:
        vertex.co.x *= scale_at_z(vertex.co.z)
    fitted_bins: list[list[float]] = [[] for _ in range(bin_count)]
    for vertex in vertices:
        index = min(bin_count - 1, max(0, int((float(vertex.co.z) - low_z) / height * (bin_count - 1))))
        fitted_bins[index].append(float(vertex.co.x))
    fitted_width_errors = []
    for sample_index, sample in enumerate(samples):
        width = width_near(fitted_bins, sample_index)
        if width > 0:
            fitted_width_errors.append(
                abs(width - float(sample["width_over_height"]) * height) / height
            )
    report = {
        "method": "height_varying_symmetric_x_scale",
        "strength": strength,
        "source_width_over_height": measurements["subject_width_over_height"],
        "minimum_x_scale": round(min(scales), 6),
        "maximum_x_scale": round(max(scales), 6),
        "mean_absolute_width_error_before": round(
            sum(abs(current - target) / height for current, target in zip(current_widths, target_widths)) / len(samples), 6,
        ),
        "mean_absolute_width_error_after": round(sum(fitted_width_errors) / max(1, len(fitted_width_errors)), 6),
        "profile_samples": len(samples),
        "depth_policy": "unchanged Atlas anatomy prior",
    }
    return report, scale_at_z
